name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint Python Files
      run: flake8 core/python/

# TODO: run pytest once the code completed
#    - name: Run Tests
#      run: pytest
