name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.2

    - name: Validate Terraform Files
      run: terraform validate

    - name: Format Check
      run: terraform fmt -check -recursive

    - name: Lint Terraform Files
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        tflint --init
        tflint

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve
